spring:
  application:
    name: store
  jpa:
    hibernate:
      ddl-auto: validate
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_IN_MS}

springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED}
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
